name: Build .exe

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_Freeze

      - run: |
          python build.py build

      - shell: pwsh
        run: |
          Get-ChildItem -Recurse

      - shell: pwsh
        run: |
          Get-ChildItem -Recurse -Filter *.exe

      - uses: actions/upload-artifact@v4
        with:
          name: app_debug
          path: build/app_debug
