name: Debug build + installer

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-windows:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: windows-latest
            artifact_name: app_debug_x64
          - runner: windows-11-arm64
            artifact_name: app_debug_a64

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_Freeze

      - name: Build executable with cx_Freeze
        run: |
          python build.py build

      - name: Upload cx_Freeze Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: dist/app_debug/**

      - name: Compile Inno Setup
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
        with:
          path: install.iss

      - name: Upload Installer Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}_installer
          path: dist/*.exe

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: uses/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install system dependencies (alien)
        run: |
          sudo apt-get update
          sudo apt-get install -y alien

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install cx_Freeze

      - name: Build .deb package with cx_Freeze
        run: |
          python build.py bdist_deb

      - name: Upload Linux .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app_debug_linux_deb
          path: dist/*.deb
